const SCRIPTS=[
 {id:'relationship',title:'Relationships',icon:'heart',color:'--c-love',blurb:'Partner, parent, child, friend or colleague',
  subj:{label:'Their name',def:'this person',chips:['my partner','my mother','my father','my child','my boss']},
  q:{def:'this person',feel:['anger','hurt','disappointment']},
  resp:['I take 100% responsibility for what I am experiencing with {n}. Something within me has attracted this, and I am ready to clean it.'],
  sorry:['I\'m sorry, {n}, for the judgments I have carried about you.','I\'m sorry, {n}, for expecting you to be someone you are not.','I\'m sorry, {n}, for the times I hurt you without realising it.','I\'m sorry, {n}, for blaming you for feelings that live inside me.','I\'m sorry, {n}, for not trying to understand your side.'],
  forgive:['Please forgive me, {n}, for trying to control you.','Please forgive me, {n}, for holding on to old grudges.','Please forgive me, {n}, for not being there when you needed me.','Please forgive me, {n}, for criticising more than I appreciated.','Please forgive me, {n}, for not giving you space to be yourself.'],
  thanks:['Thank you, {n}, for everything you have given me.','Thank you, {n}, for staying with me through difficult times.','Thank you, {n}, for the lesson this situation is teaching me. I needed it to grow.'],
  love:['I love you, {n}, just as you are.','I love you for being part of my life.','I haven\'t said it enough, but I love you.'],
  letgo:['I release everything I have been holding against you.','I set you free, and I set myself free.','I let go. I let it go.'],
  affirm:['Our relationship is healing with love.','I give and receive understanding.']},

 {id:'money',title:'Money & abundance',icon:'coin',color:'--c-thanks',blurb:'Debt, scarcity, income, loans, a new home',
  q:{def:'money',feel:['fear','worry','insecurity']},
  resp:['I take 100% responsibility for the money situation in my life. Something within me has created it, and I choose to clean it now.'],
  sorry:['I\'m sorry, money, for the fear and scarcity I have felt around you.','I\'m sorry, money, for believing there is never enough.','I\'m sorry, money, for blaming you for my problems.','I\'m sorry, money, for not learning how to care for you.'],
  forgive:['Please forgive me, money, for the limiting beliefs I carry about you.','Please forgive me, money, for keeping you at a distance.','Please forgive me, money, for not valuing you.'],
  thanks:['Thank you, money, for the home, food and comfort you provide.','Thank you, money, for taking care of my family.','Thank you, money, for every experience you have made possible.','Thank you, money, for staying with me even when I doubted you.'],
  love:['I love you, money.','I love how you flow into my life and out to others.','I welcome you with an open heart.'],
  letgo:['I release every belief that keeps me from abundance.','I let go. I let it go.'],
  affirm:['Money flows to me easily.','I am worthy of abundance.','The money I use wisely returns to me multiplied.']},

 {id:'health',title:'Health & body',icon:'leaf',color:'--c-letgo',blurb:'Skin, weight, sleep, pain or a diagnosis',
  subj:{label:'Which part of your health?',def:'my body',chips:['my body','my skin','my weight','my sleep','my back','my digestion']},
  q:{def:'my health',feel:['worry','fear','frustration']},
  note:'This practice supports your wellbeing. It does not replace medical care.',
  resp:['I take 100% responsibility for what I am experiencing with {n}. I don\'t know what inside me created this, and I am ready to clean it.'],
  sorry:['I\'m sorry, {n}, for taking you for granted.','I\'m sorry, {n}, for judging and rejecting you.','I\'m sorry, {n}, for putting work and other people before you.','I\'m sorry, {n}, for the worry and fear I have carried about you.'],
  forgive:['Please forgive me, {n}, for not resting when you asked me to.','Please forgive me, {n}, for not eating and sleeping in ways that support you.','Please forgive me, {n}, for complaining instead of listening.'],
  thanks:['Thank you, {n}, for supporting me every single day.','Thank you to every cell that keeps working without being asked.','Thank you, {n}, for showing me what needs attention.'],
  love:['I love you, {n}, just as you are.','I love you for carrying me through life.','I promise to care for you with more love.'],
  letgo:['I release all worry about {n}.','I let go and trust my body\'s wisdom.'],
  affirm:['My body knows how to heal.','I treat my body with love.']},

 {id:'anger',title:'Anger',icon:'flame',color:'--c-sorry',blurb:'When anger takes over your words or actions',
  q:{def:'this situation',feel:['anger','resentment','guilt']},
  resp:['I take 100% responsibility for my anger and for how I have acted on it.'],
  sorry:['I\'m sorry for letting anger take control of me.','I\'m sorry for the words I said in anger.','I\'m sorry for the hurt my anger has caused, to others and to me.','I\'m sorry for the guilt and resentment I have held on to.'],
  forgive:['Please forgive me for pushing my anger down instead of healing it.','Please forgive me, not because anyone else deserves it, but because I deserve peace.','Please forgive me for the actions I took when I was angry.'],
  thanks:['Thank you, anger, for showing me where my boundaries are.','Thank you, anger, for telling me something needs to change.','Thank you for this chance to heal.'],
  love:['I love you, anger, as a part of me.','I love myself, even when I am angry.'],
  letgo:['I let go of needing to be right.','I choose calm over anger.','I let go, and let God.'],
  affirm:['I choose peace.','I feel my emotions without being ruled by them.','I respond with patience.']},

 {id:'stress',title:'Stress & anxiety',icon:'wave',color:'--c-sorry',blurb:'Overthinking, fear, a restless mind',
  q:{def:'what is worrying me',feel:['fear','worry','overwhelm']},
  resp:['I take 100% responsibility for the stress and anxiety I feel. These feelings come from old memories and beliefs, and I am ready to clean them.'],
  sorry:['I\'m sorry for being so hard on myself.','I\'m sorry for believing I am not good enough.','I\'m sorry for ignoring my inner voice.','I\'m sorry for letting fear run my day.'],
  forgive:['Please forgive me for the old pain I am still carrying.','Please forgive me for fighting these feelings instead of healing them.','Please forgive me for the choices I made out of fear.'],
  thanks:['Thank you, anxiety, for trying to protect me.','Thank you for showing me what needs care.','Thank you for this chance to heal.'],
  love:['I love you, my anxious self.','I love myself, even when I am afraid.','I am safe in this moment.'],
  letgo:['I release what I cannot control.','I breathe in calm and breathe out fear.'],
  affirm:['I am safe.','I handle one thing at a time.','Peace is my natural state.']},

 {id:'self',title:'Self-love',icon:'flower',color:'--c-love',blurb:'Self-criticism, comparison, feeling not enough',
  q:{def:'myself',feel:['guilt','shame','self-doubt']},
  resp:['I take 100% responsibility for how I have treated myself.'],
  sorry:['I\'m sorry, dear self, for criticising you so often.','I\'m sorry, dear self, for comparing you to others.','I\'m sorry, dear self, for putting everyone else first.','I\'m sorry, dear self, for not listening when you were tired.'],
  forgive:['Please forgive me for the harsh words I have said to you.','Please forgive me for not believing in you.','Please forgive me for hiding who you really are.'],
  thanks:['Thank you for carrying me through everything.','Thank you for never giving up on me.','Thank you for all you do each day.'],
  love:['I love you, dear self.','I love you exactly as you are.','It doesn\'t matter who else accepts you. I accept you.'],
  letgo:['I release the need to be perfect.','I give myself a warm hug.'],
  affirm:['I am worthy of love.','I treat myself with kindness.','I am enough.']},

 {id:'exam',title:'Exams & work',icon:'book',color:'--c-forgive',blurb:'Exams, interviews, presentations, sessions',
  subj:{label:'What is coming up?',def:'this exam',chips:['this exam','my interview','my presentation','my new job','my sessions']},
  q:{def:'this exam',feel:['fear','nervousness','self-doubt']},
  resp:['I take 100% responsibility for how I feel about {n}.'],
  sorry:['I\'m sorry for the fear I carry about {n}.','I\'m sorry for doubting my ability.','I\'m sorry for putting things off.'],
  forgive:['Please forgive me for expecting to fail.','Please forgive me for comparing myself with others.','For any memory or block within me that stands in the way of {n}, please forgive me.'],
  thanks:['Thank you for the chance to learn and grow.','Thank you for everything I already know.'],
  love:['I love you, {n}.','I love my mind for everything it can hold.'],
  letgo:['I release my fear of the result.','I let go, and let God.'],
  affirm:['I remember what I have learned.','I am calm and focused.','I do my best and trust the outcome.']},

 {id:'habit',title:'Habits & addiction',icon:'link',color:'--c-letgo',blurb:'Smoking, sugar, scrolling, any habit you want to drop',
  subj:{label:'Which habit?',def:'this habit',chips:['smoking','sugar','my phone','alcohol','overeating']},
  q:{def:'this habit',feel:['craving','guilt','frustration']},
  resp:['I take 100% responsibility for {n} in my life.'],
  sorry:['I\'m sorry, body, for what {n} has done to you.','I\'m sorry for using {n} to escape my feelings.','I\'m sorry for ignoring the people who worry about me.'],
  forgive:['Please forgive me for every time I said "tomorrow".','Please forgive me for not finding kinder ways to cope.'],
  thanks:['Thank you, {n}, for comforting me when I didn\'t know another way.','Thank you for showing me what I need to heal.'],
  love:['I love my body and choose to protect it.','I love myself enough to change.'],
  letgo:['I let go of {n}. I no longer need it.'],
  affirm:['I am free.','I choose health.']},

 {id:'stuck',title:'Feeling stuck',icon:'mountain',color:'--c-guide',blurb:'Doubt, hesitation, a goal that won\'t move',
  subj:{label:'Where do you feel stuck?',def:'this goal',chips:['this goal','my career','my business','my sessions']},
  q:{def:'this goal',feel:['doubt','fear of failure','fear of rejection']},
  resp:['For every doubt and fear I carry about {n}, I take 100% responsibility.'],
  sorry:['I\'m sorry for doubting myself.','I\'m sorry for waiting for everything to be perfect.'],
  forgive:['Please forgive me for worrying about what others will think.','For any memory or block within me that is holding me back, please forgive me.'],
  thanks:['Thank you for this pause. It is preparing me.','Thank you, {n}, for helping me grow.'],
  love:['I love you, {n}.','I love the part of me that feels stuck.'],
  letgo:['I release and erase every block. I let go, and let God.','I take one small step today.'],
  affirm:['Everything is perfect as it is.','I move forward with trust.']},

 {id:'inner',title:'Inner child healing',icon:'child',color:'--c-guide',blurb:'A guided meditation to meet your younger self',noQuantum:true,
  guide:['Sit comfortably. Breathe in slowly, and breathe out. Let your eyes close.',
    'Picture a warm golden sun above your head. Let its light fill you, down to your toes.',
    'Think of a situation or person that is troubling you now. See it and hear it clearly.',
    'Notice where you feel it in your body. Stay with that feeling for a few breaths.',
    'Let a childhood memory with the same feeling come up. How old are you?',
    'Picture your younger self. Look into their eyes and say: "Hello. I am you from the future. I have come to help you."',
    'Place a hand on their shoulder. "I\'m so sorry you went through this. I\'m sorry I haven\'t looked after you until now."',
    '"Please forgive me. Thank you. I love you."',
    'Ask: "Will you let me help heal your pain?" Wait for their answer.',
    'Let the golden light hold you both. When you are ready, begin the four phrases.']}
];

const FEELINGS=['anger','hurt','sadness','fear','worry','guilt','shame','resentment','jealousy','helplessness','disappointment','self-doubt','overwhelm','frustration','insecurity','craving','nervousness'];
