const {chromium}=require('playwright');
(async()=>{const b=await chromium.launch({args:['--autoplay-policy=no-user-gesture-required']});const p=await b.newPage({viewport:{width:390,height:844}});p.setDefaultTimeout(5000);
const errs=[];p.on('pageerror',e=>errs.push(e.message));await p.route(/fonts\.g/,r=>r.abort());
await p.goto('file://'+process.cwd()+'/app.html',{waitUntil:'domcontentloaded'});const r=[];const shot=async n=>{await p.waitForTimeout(700);await p.screenshot({path:'shots/h_'+n+'.png'})};
const lat=async sel=>{const t=await p.textContent(sel);return (t.replace(/Return to Peace|I Choose Peace|Ho.oponopono/g,'').match(/[A-Za-z]{3,}/g)||[])};
await p.click('.onb [data-a="setlang"][data-v="hi"]');await shot('splash');r.push(['splash switches to Hindi',(await p.textContent('#view')).includes('होʼओपोनोपोनो')||(await p.textContent('#view')).includes('हीलिंग')]);
await p.click('[data-v="onb2"]');await p.click('[data-a="finishonb"]');await p.fill('#onbnm','सीमा');await shot('name');await p.click('[data-a="onbnamego"][data-v="1"]');await shot('home');
let l=await lat('#view');r.push(['home has no English left ('+l.slice(0,6)+')',l.length===0]);r.push(['nav in Hindi',(await lat('#nav')).length===0]);
await p.click('.tile[data-v="situations"]');await shot('sits');await p.click('.ccard[data-p="relationships"]');await p.click('[data-v="script"]');await shot('setup');l=await lat('#view');r.push(['script setup in Hindi ('+l.slice(0,6)+')',l.length===0]);
await p.click('.chip[data-a="ssubj"] >> nth=1');await p.click('[data-a="sbegin"]');await p.waitForTimeout(500);await shot('reader');const line=await p.textContent('#stage');
r.push(['script line in Hindi with the chosen name',/[ऀ-ॿ]/.test(line)&&(line.match(/[A-Za-z]{3,}/g)||[]).length===0]);
r.push(['feminine wording by default',/ती हूँ/.test(line)&&!/\{\{/.test(line)]);
await p.click('[data-a="rclose"]');await p.click('[data-a="rclose"]').catch(()=>{});await p.waitForTimeout(300);
await p.evaluate(()=>{const s=JSON.parse(localStorage.getItem('hoo.app.v2'));s.gender='m';localStorage.setItem('hoo.app.v2',JSON.stringify(s))});await p.reload({waitUntil:'domcontentloaded'});
r.push(['masculine wording when chosen',await p.evaluate(()=>window.__T('I release, I let go, I let God.'))==='मैं छोड़ता हूँ, मैं जाने देता हूँ, मैं ईश्वर को सौंपता हूँ।']);
r.push(['numbers kept',(await p.evaluate(()=>window.__T('3 of 5 complete'))).includes('3')&&(await p.evaluate(()=>window.__T('3 of 5 complete'))).includes('5')]);
r.push(['quantum line builds in Hindi',!/[A-Za-z]{3,}/.test(await p.evaluate(()=>window.__T('For the anger, hurt and fear I feel about my mother, I’m sorry.')))]);
console.log(await p.evaluate(()=>[window.__T('For the anger, hurt and fear I feel about my mother, I’m sorry.'),window.__T('Morning Mantra is part of Premium'),window.__T('Day 4 of 21 · Calm the worry'),window.__T('I love you, fear. I accept you.')].join('\n')));
await p.click('.tile[data-v="affirmations"]');await shot('morning');await p.click('[data-a="mplay"][data-v="gratitude"]');await shot('car');r.push(['affirmation card in Hindi',/[ऀ-ॿ]/.test(await p.textContent('.acard.on .mtext'))]);
await p.click('[data-a="mshare"]');await p.waitForSelector('.sheet img');await shot('card');await p.evaluate(()=>document.querySelector('[data-a="closesheet"]').click());await p.click('[data-a="mclose"]');await p.waitForTimeout(300);
await p.click('.nav [data-v="home"]');await p.click('.chhome');await p.click('[data-a="chstart"]');await shot('ch');l=await lat('#view');r.push(['challenge in Hindi ('+l.slice(0,6)+')',l.length===0]);
await p.click('.chtoday [data-a="chdo"]');await p.waitForTimeout(25000);const g=await p.textContent('#guided');r.push(['song lyrics stay English and follow the new timing ('+g+')',g==='I release what I no longer need']);await shot('player');
await p.click('[data-a="pclose"]');await p.click('.nav [data-v="more"]');await shot('more');await p.click('[data-a="langsheet"]');await shot('lang');await p.click('.sheet [data-a="setlang"][data-v="en"]');
r.push(['switching back to English works',(await p.textContent('#view')).includes('Backup & Restore')]);
console.log(r.map(x=>(x[1]?'PASS ':'FAIL ')+x[0]).join('\n'),'\nERRORS',errs);await b.close()})();
