const {chromium}=require('playwright');const sh='shots/m-';
(async()=>{const b=await chromium.launch();const p=await b.newPage({viewport:{width:390,height:844}});p.setDefaultTimeout(4000);
const errs=[];p.on('pageerror',e=>errs.push(e.message));await p.route(/fonts\.g/,r=>r.abort());
await p.goto('file://'+process.cwd()+'/app.html',{waitUntil:'domcontentloaded'});
const log=[];const ok=(c,m)=>log.push((c?'PASS ':'FAIL ')+m);const shot=async n=>{await p.waitForTimeout(700);await p.screenshot({path:sh+n+'.png'})};
const dead=async n=>{const miss=await p.evaluate(()=>[...new Set([...document.querySelectorAll('[data-a]')].map(e=>e.dataset.a))].filter(a=>!window.__ACT_KEYS.includes(a)));ok(!miss.length,'no dead actions '+n+' '+miss)};
await p.click('[data-v="onb2"]');await p.click('[data-a="finishonb"]');await p.click('[data-a="onbnamego"][data-v=""]');await shot('01-home');await dead('home');
ok((await p.locator('.slide').count())===5,'home carousel 5 slides');
await p.click('.cdots button[data-v="2"]');await p.waitForTimeout(900);ok(await p.evaluate(()=>document.querySelectorAll('.slide')[2].classList.contains('on')),'dot moves carousel');await shot('02-home-slide2');
await p.waitForTimeout(500);await p.click('.slide.on');await shot('03-morning');await dead('morning');ok((await p.textContent('h1')).includes('Start Your Mornings'),'slide opens morning');
await p.fill('[data-g="have"][data-i="0"]','Clean air and water');await p.fill('[data-g="have"][data-i="1"]','My health');await p.fill('[data-g="coming"][data-i="0"]','A clear, healthy body');await p.fill('[data-g="coming"][data-i="1"]','Peace with my brother');await p.fill('[data-g="coming"][data-i="2"]','All loans repaid');
await p.click('[data-a="mreason"] >> nth=0');
await p.click('.msec[data-v="love"]');await shot('04-aff-love');ok(await p.isVisible('.acard.on'),'affirmation carousel opens');await dead('carousel');
for(let i=0;i<3;i++){await p.click('.acard.on .mface');await p.waitForTimeout(150)}await p.waitForTimeout(1500);
ok((await p.textContent('#mcount')).startsWith('2 of'),'3 taps advance '+(await p.textContent('#mcount')));
await p.click('[data-a="mfav"]');await p.click('[data-a="mnav"][data-v="1"]');await p.waitForTimeout(900);await shot('05-aff-card');
await p.click('[data-a="mauto"]');await p.waitForTimeout(300);await p.click('[data-a="mauto"]');
// swipe via scroll
await p.evaluate(()=>{const t=document.getElementById('mtrack');t.scrollTo({left:t.clientWidth*11})});await p.waitForTimeout(800);ok((await p.textContent('#mcount')).startsWith('12 of'),'swipe to last');
await p.click('[data-a="mnav"][data-v="1"]');await p.waitForTimeout(700);await shot('06-aff-done');ok(await p.isVisible('.mdone'),'finish screen');
await p.click('[data-a="mclose2"]');await p.waitForTimeout(400);ok(!(await p.isVisible('#player')),'closes');
await p.click('[data-a="mplay"][data-v="all"]');await p.waitForTimeout(600);await shot('07-aff-grat');ok((await p.textContent('#mcount')).includes('70'),'full ritual count '+await p.textContent('#mcount'));
await p.keyboard.press('Escape');await p.waitForTimeout(400);ok(!(await p.isVisible('#player')),'escape closes');
await p.reload({waitUntil:'domcontentloaded'});await p.waitForTimeout(500);
await p.click('.tile[data-v="affirmations"]');ok((await p.inputValue('[data-g="have"][data-i="0"]'))==='Clean air and water','gratitude persists');
await p.click('[data-a="back"]');await p.click('.tile[data-v="daily"]');ok(await p.evaluate(()=>document.querySelectorAll('.num.done').length>=1),'gratitude practice marked');
await p.click('.nav [data-v="progress"]');await p.waitForTimeout(1200);await shot('08-progress');
await p.click('.nav [data-v="more"]');await p.click('.li[data-v="favorites"]');await p.click('[data-a="favtab"][data-v="aff"]');ok((await p.locator('.card.row').count())===1,'morning favourite listed');await shot('09-favs');
console.log(log.join('\n'));console.log('ERRORS',errs);await b.close()})();
